![ngo_project_image](ngo_project_image.jpg)

GoodThought NGO has been a catalyst for positive change, focusing its efforts on education, healthcare, and sustainable development to make a significant difference in communities worldwide. With this mission, GoodThought has orchestrated an array of assignments aimed at uplifting underprivileged populations and fostering long-term growth.

This project offers a hands-on opportunity to explore how data-driven insights can direct and enhance these humanitarian efforts. In this project, you'll engage with the GoodThought PostgreSQL database, which encapsulates detailed records of assignments, funding, impacts, and donor activities from 2010 to 2023. This comprehensive dataset includes:

- **`Assignments`:** Details about each project, including its name, duration (start and end dates), budget, geographical region, and the impact score.
- **`Donations`:** Records of financial contributions, linked to specific donors and assignments, highlighting how financial support is allocated and utilized.
- **`Donors`:** Information on individuals and organizations that fund GoodThought’s projects, including donor types.

Refer to the below ERD diagram for a visual representation of the relationships between these data tables:
<img src="erd.png" alt="ERD" width="50%" height="50%">


You will execute SQL queries to answer two questions, as listed in the instructions. Good luck!

In [28]:
-- highest_donation_assignments
WITH D_type AS (SELECT d.assignment_id, ROUND(SUM(d.amount), 2)AS rounded_total_donation_amount, r.donor_type
			 	 FROM donations AS d
				INNER JOIN donors AS r USING(donor_id)
			   GROUP BY d.assignment_id, r.donor_type)

SELECT a.assignment_name, a.region, D.rounded_total_donation_amount, D.donor_type
FROM D_type AS D
INNER JOIN assignments AS a USING(assignment_id)
ORDER BY rounded_total_donation_amount DESC
LIMIT 5;

   assignment_name region  rounded_total_donation_amount    donor_type
0  Assignment_3033   East                        3840.66    Individual
1   Assignment_300   West                        3133.98  Organization
2  Assignment_4114  North                        2778.57  Organization
3  Assignment_1765   West                        2626.98  Organization
4   Assignment_268   East                        2488.69    Individual

In [29]:
-- top_regional_impact_assignments
WITH donation_list AS (SELECT DISTINCT assignment_id, ROUND(COUNT(donation_id), 2) AS num_total_donations
					   FROM donations 
					  	GROUP BY assignment_id),


rank_impact AS (SELECT DISTINCT a.assignment_name, a.region, a.impact_score, d.num_total_donations,
						ROW_NUMBER() OVER(PARTITION BY region ORDER BY impact_score DESC) AS rank_n
					FROM assignments AS a 
			   		 JOIN donation_list AS d USING(assignment_id)
			   			WHERE d.num_total_donations > 0)

SELECT assignment_name, region, impact_score, num_total_donations
FROM rank_impact
WHERE rank_n = 1
ORDER BY region ASC;

   assignment_name region  impact_score  num_total_donations
0   Assignment_316   East         10.00                  2.0
1  Assignment_2253  North          9.99                  1.0
2  Assignment_3547  South         10.00                  1.0
3  Assignment_2794   West          9.99                  2.0